version: "3.9"

services:
  portfolio:
    build: .
    container_name: portfolio_app
    ports:
      - "8080:8080"
    
    # Run as non-root user (extra security)
    user: "1001:1001"

    # Read-only filesystem (security hardening)
    read_only: true

    # Limit privileges
    security_opt:
      - no-new-privileges:true

    restart: unless-stopped
