name: Deploy to VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Deploy Portfolio
        run: |
          set -e

          cd /home/aaysha/portfolio/aaysha-portfolio

          echo "Pulling latest code..."
          git fetch origin main
          git reset --hard origin/main

          echo "Restarting Docker..."
          docker compose down
          docker compose up -d --build

          echo "Done."
